### ISSUE TITLE
홈 관련 페이지 UI 구현

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#34]
### Feature

홈과 홈 내에 세부페이지들의 UI를 구현합니다.

### Todo

- [x] 홈 탭 메인 페이지 UI 구현
- [x] 대장툰 페이지 UI 구현
- [ ] 레시피 릴스 페이지 UI 구현
- [x] 약 카드뉴스 UI 구현
- [ ] 상품추천 뉴스레터 UI 구현
