### ISSUE TITLE
커뮤니티 UI 구현

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#46]
### Feature

커뮤니티 내 UI들을 구현합니다.

### Todo

- [x] 커뮤니티 메인 탭 UI 구현
- [x] 카테고리별 게시판 UI 구현
- [x] 게시글 UI 구현
- [ ] 검색 UI 구현
- [ ] 내가 쓴 글 UI 구현
- [ ] 댓글단 글 UI 구현
- [ ] 글쓰기 UI 구현
