### ISSUE TITLE
배변일지 화면 및 기록 UI 구현

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#67]
### Feature

배변일지 탭에서 사용자의 배변일지 및 기록 화면의 UI를 구현합니다.

### Todo

- [x] 배변일지 메인 탭 프로필 UI 구현
- [x] 배변일지 캘린더 UI 구현
- [x] 배변일지 날짜 내 기록보는 UI 구현
- [x] + 버튼 과 누르면 나오는 메뉴 UI 구현
- [x] 배변일지 기록 모달 UI 구현
