### ISSUE TITLE
배변 분석(AI) 관련 UI 구현

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#68]
### Feature

AI를 이용한 배변 분석과 관련된 UI들을 구현합니다.

### Todo

- [x] 배변일지 메인 탭 화면 최하단에 AI 배변분석 결과 항목 UI 구현
- [x] + 버튼 누를 시 배변 AI 분석 버튼 추가
- [x] 비전 AI를 이용한 배변 사진 분석 UI 구현
- [x] 배변 분석 전 입력받는 폼 UI 구현
- [x] 배변분석 결과 UI 구현
