### ISSUE TITLE
대장간 UI 구현

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#70]
### Feature

대장간에서 필요한 UI를 구현합니다.

### Todo

- [x] 대장간 메인화면 UI 구현
- [x] 각 카테고리 구분 UI 구현
- [x] 검색 페이지 UI 구현
- [x] 관심상품 UI 구현
