### ISSUE TITLE
대장간 API 연동

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#75]
### Feature

대장간 관련 API를 구현하고 연동합니다.

### Todo

- [X] 상품 API 및 쿼리 작성
- [x] 상품 검색 기능 구현
- [ ] 카테고리별 상품 메뉴 기능 구현
- [x] 이번주 인기 상품 기능 구현
- [X] 개인 맞춤화 장건강 상품 기능 구현
- [X] 배너 구현
