### ISSUE TITLE
배변일지 기능 연동

### ISSUE THREAD

**Issue by yeophs** [daejangjangi/daejangjangi-app#80]
### Feature

구현되어있는 배변일지 UI와 API를 연동합니다.

### Todo

- [x] 배변기록 추가 구현
- [x] 배변기록 수정 구현
- [x] 배변기록 불러오기 구현
- [x] 배변일지 삭제 구현
- [x] 배변 AI 분석 > 배변 이미지 분석 구현
- [x] 배변 AI 분석 > 배변 챗봇 분석 구현
